a=app.install(core,function()error('Closed identity gate must never construct firing backend')end,function()return ''end)
tick(0,false);fire=true;tick(20);tick(120)
assert(a:get_state().weapon.name=='P-2 Peacemaker' and a:get_state().eligibility.category=='ASSIST')
assert(not a:get_state().identity_valid and not a:get_state().effective and not a:get_state().repeat_active)
assert(backend.writes==0 and backend.starts==0 and a:status().counters.input_checks==0)
resource_hash='968211c0033dce64';tick(240)
assert(a:get_state().user_enabled and a:get_state().eligibility.category=='IGNORE_NATIVE_AUTO')
tick(400,true);assert(not a:get_state().user_enabled)
resource_hash='05e4e5c2db6e44a2';tick(600,false);assert(not a:get_state().user_enabled)
assert(not a:status().failed and core.Diagnostics:Status().scheduler.failures==0)
shutdown();assert(core.Diagnostics:Status().scheduler.active==0 and not a:get_state().effective)
