-- Runs only against an isolated in-memory copy with the gate opened by tests.
a=app.install(core,function()return backend end,function()return ''end)
assert(app.install(core,function()error('duplicate')end)==a)
assert(a:status().active and a:get_state().user_enabled,
    'An absent INI must use the default enabled state')
-- Model ship/loading followed by mission entry. Startup ON must work without
-- any toggle input once Fire is released and then pressed in valid gameplay.
gameplay=false;tick(0,false);assert(a:status().active and a:get_state().user_enabled)
gameplay=true;tick(10,false);assert(a:get_state().effective)
fire=true;tick(20);assert(backend.lease and a:get_state().repeat_active)
local starts=backend.starts
resource_hash='968211c0033dce64';entity_id=1002;tick(40)
assert(not backend.lease and a:get_state().user_enabled and not a:get_state().effective,'Mixed weapon stops, toggle persists')
resource_hash='05e4e5c2db6e44a2';entity_id=1001;tick(60)
assert(backend.starts==starts,'No resume across swap without Fire release')
fire=false;tick(80);fire=true;tick(100);assert(backend.lease)
entity_id=1003;tick(120);assert(not backend.lease,'Same semantic weapon, different entity stops')
fire=false;tick(140);fire=true;tick(160);assert(backend.lease)
resource_hash='0000000000000001';tick(180);assert(not backend.lease,'Unknown hash stops')
resource_hash='05e4e5c2db6e44a2';fire=false;tick(200);fire=true;tick(220)
avatar_ok=false;tick(240);assert(not backend.lease and not a:get_state().identity_valid)
avatar_ok=true;fire=false;tick(260);fire=true;tick(280);assert(backend.lease)
unit=124;tick(300);assert(not backend.lease,'Player transition stops')
fire=false;tick(320);fire=true;tick(340);assert(backend.lease)
chat=true;tick(360);assert(not backend.lease and a:get_state().user_enabled,'Chat suppresses without changing preference')
chat=false;tick(380);assert(not backend.lease and a:get_state().user_enabled,'Closing chat requires release')
fire=false;tick(400);fire=true;tick(420);menu=true;tick(440)
assert(not backend.lease and a:get_state().user_enabled,'Menu suppression preserves ON preference')
menu=false;fire=false;tick(460);fire=true;tick(480);focused=false;tick(500)
assert(not backend.lease and a:get_state().user_enabled,'Focus suppression preserves ON preference')
focused=true;fire=false;tick(520);fire=true;tick(540);gameplay=false;tick(560)
assert(not backend.lease and a:get_state().user_enabled,'Ship transition preserves ON preference')
gameplay=true;fire=false;tick(580);fire=true;tick(600);assert(backend.lease)
tick(800,true);assert(not a:get_state().user_enabled and not backend.lease and a:status().counters.toggles==1)
resource_hash='35a61296619cc47e';entity_id=1004;fire=false;tick(1000,false)
assert(a:get_state().eligibility.category=='EXCLUDE_CHARGE_HOLD' and not a:get_state().user_enabled)
gameplay=false;tick(1100,false);assert(not a:get_state().user_enabled,'OFF survives return to ship')
resource_hash='05e4e5c2db6e44a2';entity_id=1001;gameplay=true;tick(1200,false)
assert(not a:get_state().user_enabled and not a:get_state().effective,'Toggle OFF survives swaps')
tick(1400,true);assert(a:get_state().user_enabled and a:status().counters.toggles==2)
fire=false;tick(1420);fire=true;tick(1440);assert(backend.lease)
local snapshot=a:get_state();snapshot.weapon.resource_hash='bad';assert(a:get_state().weapon.resource_hash~='bad')
assert(a:stop().ok and not backend.lease and not a:get_state().effective)
local lookups=identity_calls;tick(1600,false);assert(identity_calls==lookups,'Cancellation prevents further identity reads')
-- A persisted explicit OFF preference remains OFF across startup and mission
-- entry. The normal toggle path is covered above for the default ON state.
gameplay=false;fire=false
b=app.install(core,function()return backend end,function()return 'user_enabled=false'end)
assert(not b:status().active and not b:get_state().user_enabled)
gameplay=true;fire=true;tick(1620,false)
assert(not backend.lease and not b:get_state().user_enabled)
fire=false;tick(1640,false)
assert(not b:status().active and not b:get_state().user_enabled)
assert(b:stop().ok)
shutdown();local s=core.Diagnostics:Status()
assert(s.input.active==0 and s.scheduler.active==0 and s.events.active==0)
assert(a:status().counters.errors==0 and s.scheduler.failures==0)
