-- Warrant-specific lease, release, OFF, and unknown-identity safety checks.
a=app.install(standalone_host,function()return backend end,function()return ''end)
gameplay=true;resource_hash='cf8934ff6567a42d';entity_id=5010;fire=false;tick(0)
fire=true;tick(20)
assert(a:get_state().effective and backend.lease,'Warrant repeats ordinary Fire when enabled')
fire=false;tick(40)
assert(not backend.lease and not a:get_state().repeat_active,'Physical Fire release stops assistance')
fire=true;tick(60);assert(backend.lease)
tick(80,true)
assert(not a:get_state().user_enabled and not backend.lease,'OFF suppresses Warrant assistance')
resource_hash='0000000000000001';entity_id=5011;fire=false;tick(100);fire=true;tick(120)
assert(not a:get_state().effective and not backend.lease,'Unknown identity remains fail-closed while OFF')
assert(a:stop().ok and not backend.lease)
shutdown()
print('test_warrant_safety: all checks passed')
