-- Input ownership checks, not a simulation of accepted live weapon shots.
local Policy=require('weapon_policy')
local Fixture=require('native_transition_fixture')
local peace,eruptor,amr,commando='05e4e5c2db6e44a2','b6aff2195568767f','89c5493e08ca4207','5990123d142b16cb'
local policy=Policy.new()
assert(policy:classify(eruptor).assist_role=='CADENCE_CONTROL')
assert(policy:classify(eruptor).native_held_behavior=='native_hold_to_repeat')
assert(policy:classify(peace).assist_role=='REPEAT_ASSIST')
assert(policy:classify(amr).assist_role=='SPECIAL')
assert(policy:classify(commando).allowed)
assert(policy:classify('968211c0033dce64').assist_role=='UNSUPPORTED')
for profile,rpm in pairs({slower_27=27,balanced_28=28,max_32=32})do
    local f=Fixture.new('user_enabled=false\neruptor_profile='..profile)
    local original=f.u32(0x0012ff43)..f.u32(1)..f.u32(2)..f.float(0)..f.float(.5)
    f:put(f.BUCKET,f.u32(0x20009)..f.u32(3)..original:rep(3))
    f:weapon(eruptor);f:input(1,.1,true,2);f:tick()
    local input=f:bytes(f.CONTROLS+0x1c88,32)
    for _=1,60 do f:tick(16667)end
    assert(f.writes==0 and not f.backend.lease)
    assert(f:bytes(f.CONTROLS+0x1c88,32)==input,'OFF suppressed native held Fire')
    assert(f:bytes(f.BUCKET+8,60)==original:rep(3))
    assert(f.consumer:get_hud_state().visible and not f.consumer:get_hud_state().enabled)
    f.host.callbacks.toggle.callback();f:tick()
    assert(not f.backend.lease,'Enabling while held bypassed release guard')
    f:input(0,0,false,2);f:tick();f:input(1,.1,true,2);f:tick()
    assert(f.backend.lease and f.backend.repeat_seconds==60/rpm)
    assert(f.consumer:get_hud_state().enabled)
    f.host.callbacks.toggle.callback()
    assert(not f.backend.lease and f:bytes(f.BUCKET+8,60)==original:rep(3))
    local writes=f.writes
    f:input(1,2,true,2);f:tick()
    assert(f.writes==writes and f:bytes(f.CONTROLS+0x1c88,32):byte(1)==1,
        'Native repetition while OFF is not a restore failure')
    f:weapon('968211c0033dce64');f:tick()
    assert(not f.consumer:get_hud_state().visible and not f.backend.lease)
    assert(f.consumer:stop().ok)
end
-- A manual-edge fixture stays stock while OFF; ON uses the existing repeat lease.
local f=Fixture.new('user_enabled=false')
f:weapon(peace);f:input(1,.1,true,0);f:tick()
f:input(1,1,false,0);f:tick()
assert(f.writes==0 and not f.backend.lease)
assert(f:bytes(f.CONTROLS+0x1c88,32):byte(1)==0,'OFF injected a manual Fire pulse')
f:input(0,0,false,0);f:tick();f.host.callbacks.toggle.callback();f:tick()
f:input(1,.1,true,0);f:tick();assert(f.backend.lease)
f:weapon(eruptor);f:tick();assert(not f.backend.lease and f:restored())
assert(f.consumer:status().wait_release,'Held swap retained the old lease')
assert(f.consumer:stop().ok)
print('Cadence Control metadata, native-held OFF preservation, 27/28/32 ON/OFF, manual-edge OFF, supported/unsupported and held swap passed')
